# NumPy - Indexing

In this unit, you are going to learn how to select rows, columns and values from a NumPy array.

You will learn about:
- creating 1D and 2D arrays
- selecting elements and slices of arrays

### Examples from the introduction to creating and indexing arrays


#### creating 1D and 2D arrays

In [13]:
# creating a 1D array
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


In [17]:
# creating a 2D array
my_array = np.array([[1, 2, 3, 4, 5], 
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15]])
print(my_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [18]:
# selecting the first row
row_1 = my_array[0]
print(row_1)

[1 2 3 4 5]


In [19]:
# creating a slice of the first two rows
slice = my_array[:2]
print(slice)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [20]:
# selecting the third element in the first row
print(my_array[0, 2])

3


In [21]:
# selecting the third column
print(my_array[:, 2])

[ 3  8 13]


In [22]:
# selecting non-adjacent elements
print(my_array[[0, -1]])

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


### Task 1: Convert a list of list to a numpy array

Below are three lists with data on the La Lakers basketball team. Since in NumPy you cannot label the columns and rows of your data, we had to store the data, column names and player names in separate lists. We are only going to conver the lakers_data list of lists, which has the actual player statistics, to a numpy array.

1. Import the numpy library.
2. Convert the lakers_data list to a numpy array.
3. Print the array.

In [2]:
# run this cell to load the lists into Python

lakers_data = [[1.0, 1.0, 67.0, 34.6, 9.6, 19.4, 3.9, 5.7, 7.8, 10.2, 1.2, 0.5, 25.3],
               [2.0, 4.0, 62.0, 34.4, 8.9, 17.7, 7.2, 8.5, 9.3, 3.2, 1.5, 2.3, 26.1],
               [3.0, 2.0, 69.0, 25.5, 3.4, 7.3, 1.1, 1.5, 2.1, 1.6, 0.8, 0.2, 9.3],
               [4.0, 4.0, 61.0, 25.0, 4.8, 11.0, 1.9, 2.5, 4.5, 1.3, 0.5, 0.4, 12.8],
               [5.0, 2.0, 68.0, 24.8, 2.9, 7.0, 0.5, 0.7, 3.3, 1.3, 1.3, 0.5, 8.0],
               [6.0, 2.0, 49.0, 24.2, 3.5, 7.8, 0.4, 0.5, 2.3, 1.3, 0.9, 0.1, 8.6],
               [7.0, 2.0, 7.0, 23.6, 4.4, 10.4, 2.0, 2.3, 1.9, 2.4, 0.6, 0.6, 11.9],
               [8.0, 1.0, 48.0, 20.5, 2.9, 6.8, 0.6, 0.9, 3.0, 5.0, 0.8, 0.0, 7.1],
               [9.0, 5.0, 69.0, 18.9, 2.9, 4.0, 1.6, 3.1, 7.3, 0.7, 0.4, 1.1, 7.5],
               [10.0, 2.0, 64.0, 18.4, 1.9, 4.5, 1.1, 1.5, 1.9, 1.9, 1.1, 0.3, 5.5],
               [11.0, 5.0, 68.0, 16.6, 2.9, 4.5, 0.8, 1.2, 5.7, 0.5, 0.5, 1.4, 6.6],
               [12.0, 4.0, 14.0, 14.2, 2.0, 4.9, 0.4, 0.4, 3.2, 0.6, 0.4, 0.4, 5.3],
               [13.0, 3.0, 6.0, 13.5, 2.3, 5.0, 0.3, 0.7, 1.2, 1.0, 1.3, 0.2, 5.7],
               [14.0, 2.0, 6.0, 13.2, 1.2, 3.7, 0.3, 0.3, 0.8, 0.5, 0.2, 0.0, 2.8],
               [15.0, 1.0, 44.0, 11.5, 2.1, 4.9, 0.3, 0.3, 1.2, 1.1, 0.3, 0.0, 5.1],
               [16.0, 2.0, 41.0, 11.1, 1.5, 3.9, 0.2, 0.4, 1.1, 0.3, 0.2, 0.1, 4.2],
               [17.0, 5.0, 1.0, 9.0, 3.0, 6.0, 0.0, 0.0, 5.0, 1.0, 0.0, 0.0, 6.0],
               [18.0, 4.0, 45.0, 8.1, 0.5, 1.3, 0.0, 0.0, 1.2, 0.6, 0.3, 0.1, 1.5],
               [19.0, 4.0, 5.0, 4.0, 0.6, 0.6, 0.2, 0.4, 0.6, 0.4, 0.0, 0.0, 1.4],
               [20.0, 2.0, 2.0, 2.5, 0.0, 0.5, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0]]

column_names = ['Rank',
                'Position',
                'Games',
                'Minutes',
                'Shots made',
                'Shots attempted',
                'Free throws',
                'Free throws attempted',
                'Rebounds',
                'Assists',
                'Steals',
                'Blocks',
                'Points']

player_names = ['LeBron James',
                'Anthony Davis',
                'Kentavious Caldwell-Pope',
                'Kyle Kuzma',
                'Danny Green',
                'Avery Bradley',
                'Dion Waiters',
                'Rajon Rondo',
                'Dwight Howard',
                'Alex Caruso',
                'JaVale McGee',
                'Markieff Morris',
                'Talen Horton-Tucker',
                'J.R. Smith',
                'Quinn Cook',
                'Troy Daniels',
                'Devontae Cacok',
                'Jared Dudley',
                'Kostas Antetokounmpo',
                'Zach Norvell']

In [ ]:
# import numpy


# convert lakers_data to lakers_np



### Task 2: Creating subsets

1. Print the first five rows
2. Print the 'Points' column
3. Print the 'Steals' column
4. Print Points value for the second player
5. Print the last five rows.
6. Print the last five columns for the first five players

#### Tip on selecting columns

Here is a quick tip on selecting columns using the column_names list. You can use the `range()` function together with the `len()` function to print the position and name of each column.

The i variable gives you a counter to select each element from the column_names list. At the same time, you can print the i variable to know the position of the column in the array.

In [24]:
for i in range(len(column_names)):
    print(i, column_names[i])

0 Rank
1 Position
2 Games
3 Minutes
4 Shots made
5 Shots attempted
6 Free throws
7 Free throws attempted
8 Rebounds
9 Assists
10 Steals
11 Blocks
12 Points


In [1]:
# Print the first five rows


In [2]:
# Print the 'Points' column


In [3]:
# Print the 'Steals' column


In [4]:
# Print Points value for the second player


In [5]:
# Print the last five rows.


In [6]:
# Print the last five columns for the first five players
